/*
 * This source file was generated by the Gradle 'init' task
 */
package rubrica;

import rubrica.controller.PersonControllerImpl;
import rubrica.gui.PersonViewImpl;
import rubrica.model.PersonManager;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            PersonManager model = new PersonManager();
            PersonViewImpl view = new PersonViewImpl(model);

            new PersonControllerImpl(model, view);
        });
    }
}
