/*
 * This source file was generated by the Gradle 'init' task
 */
package rubrica;

import rubrica.controller.LoginController;
import rubrica.view.LoginView;

public class App {

    public static void main(String[] args) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            LoginView view = new LoginView();

            new LoginController(view);
        });
    }
}
